
# GRID LINES
DARK_GRID_LINES = "#000000"
LIGHT_GRID_LINES = "#e0e0eb"

# INPUT NODES
INPUT_PLUG = "#00b300"
INPUT_PLUG_BORDER = "#000000"
SELECTED_INPUT_PLUG_BORDER = "#e0e0eb"

# OUTPUT NODES
OUTPUT_PLUG = "#ff9900"
OUTPUT_PLUG_BORDER = "#000000"
SELECTED_OUTPUT_PLUG_BORDER = "#e0e0eb"

# NODE RECTANGLE
RECTANGLE = "#80aaff"
RECTANGLE_HEADER = "#6699ff"
RECTANGLE_BORDER = "#000000"
SELECTED_RECTANGLE_BORDER = "#e0e0eb"

# CONNECTIONS
CONNECTION_LINE = "#ffc34d"

# TEXT
TEXT_COLOR = "#ffffff"
TEXT_SELECTED_COLOR = "#ff9900"
